### ISSUE TITLE
[TODO] Fix the App, Does not run app.py

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/machinistcalc#1]
Am having problems starting the app.py

The app should start and run as a menu to choose which program to run.

**Comment by Ahmed-Z-D** [comment]
While `app.py` should be structured properly, the issue at hand is not related to this file. The problem is instead caused by the way the other files in the `app `directory have been organized. One potential solution would be to create functions that encapsulate the logic in these files, Once imported, these functions can be used within a `menu` function to resolve the issue. For instance:

````
def menu(option: int) -> None:
    options= {
        1: lathecalc,
        2: sheetmetalcalc,
        3: speedfeed,
        4: bendcalc
    }
    try:
        menu[option]()
    except KeyError: 
        print("Invalid selection")
````

**Comment by gbowne1** [comment]
I actually like that solution.  What I used was only a suggestion through some reading I did, just didn't seem to work..  I also wanted to make it easy to add other options/menu choices and or create a text UI somehow.  I know I will end up with like 10 menu choices by the time all the sub-programs are done.  

Willing to submit a PR?

**Comment by gbowne1** [comment]
My other thought was to eventually Flask.  but needed somewhere to start.

**Comment by gbowne1** [comment]
or something like:

```py
import curses

def main(stdscr):
    # Clear the screen
    stdscr.clear()

    # Create a new window with 80 rows and 24 columns
    win = curses.newwin(24, 80, 0, 0)

    # Draw the menu items in the window
    win.addstr(0, 0, "Menu:")
    win.addstr(2, 2, "1. Item 1")
    win.addstr(3, 2, "2. Item 2")
    win.addstr(4, 2, "3. Item 3")

    # Refresh the window
    win.refresh()

    # Wait for user input
    stdscr.getch()

# Initialize the curses module
curses.wrapper(main)
```

**Comment by Ahmed-Z-D** [comment]
Sure, I will submit a pull request shortly, but I want to point out that there may be another problem that could cause imprecise calculation results in the application. This problem is related to the limitations of [Floating-Point Arithmetic](https://docs.python.org/3/tutorial/floatingpoint.html),  and it is something that will need to be addressed to ensure that the calculations are dependable and precise.

P.S. While your suggestion of using `curses `is valid, I may not have adequate time to implement it in the upcoming pull request .

**Comment by gbowne1** [comment]
that's fine.  I can do some of that work with curses, as the app progresses.  curses is not needed at the moment.  I've done a little checking on some of the results, based on some we use in the workshop and its pretty close to pen and paper and calculator results.  I can only expect precision to 5, 6, 7 decimal places.
